PATH_LOG_DIR : "storage/etl/logs/"
PATH_ARCHIVE_DIR : "storage/etl/data/archive/"
PATH_DATA_BRONZE : "storage/etl/data/1_bronze/"
PATH_DATA_SILVER : "storage/etl/data/2_silver/"
PATH_DATA_GOLD : "storage/etl/data/3_gold/"
PATH_FILE_INPUT_ENEDIS_CSV : "storage/etl/data/1_bronze/conso_enedis.csv"
SCHEMA_ETL_INPUT_FILEPATH : "config/schema_bronze_data.json"
SCHEMA_SILVER_DATA_FILEPATH : "config/schema_silver_data.json"
SCHEMA_GOLDEN_DATA_FILEPATH : "config/schema_golden_data.json"
