name: ghaction-cd-volt-engine-etl-docker-img
run-name: CD${{ github.run_number }}-${{ github.event.repository.name }}-${{ github.workflow }}_${{ github.ref_name }}
on: 
    workflow_call:
      inputs:
          api-tag:
              required: true
              type: string
jobs:
    call-github-python-pytests-workflow:
      uses: fereol023/pipelines_templates/.github/workflows/github-docker-build-and-push.yml@main
      secrets:
        CR_USER: ${{ secrets.CR_USER }}
        CR_PWD: ${{ secrets.CR_PWD }}
      with:
        hasSubmodules: true
        dockerfile_path: 'api/Dockerfile.uv.distro'
        GIT_TAG: ${{ inputs.api-tag }}
        